### ISSUE TITLE
Add support for biber

### ISSUE THREAD

**Issue by JensHeinrich** [tueda/makefile4latex#11]
Biber does not exactly replicate BibTeX and has a check mode useful for a debug run
(Will try to submit a PR later today)

**Comment by tueda** [comment]
@JensHeinrich 
If you are still interested, would you try the [`biblatex` branch](https://github.com/tueda/makefile4latex/tree/biblatex)?

At least, now it seems to work for simple examples.

**Comment by JensHeinrich** [comment]
@tueda sure!
I will try it out later; forgot I wanted to build something

**Comment by JensHeinrich** [comment]
Ran it on a smaller document of mine and it works pretty good :)
thanks

**Comment by tueda** [comment]
Thank you for testing. I will merge the branch to the master.

**Comment by tueda** [comment]
The branch has been merged (though there are limitations in the DIFF mode).
