### ISSUE TITLE
Add support for bib2gls

### ISSUE THREAD

**Issue by JensHeinrich** [tueda/makefile4latex#12]
`bib2gls` provides support for bib files for glossaries-extra

**Comment by tueda** [comment]
Basic bib2gls support is now implemented. One may need to set `BIB2GLS_OPT` for the bib2gls command-line options. Dependency tracking for bib2gls input .bib files are not enabled (which causes a problem with BibTeX), so one needs manually to update the main LaTeX source, like `touch <main>.tex`. The DIFF mode also has problems with bib2gls.
